[versions]
kotlin = "2.2.21"
plugin-publish = "2.0.0"
test-logger = "4.0.0"
spotless = "8.0.0"
gson = "2.13.2"
stonecutter = "0.6.2"
architectury-loom = "1.13.457"
mod-publish = "1.0.0"
junit = "6.0.1"
junit-pioneer = "2.3.0"
mockito = "5.20.0"
mockito-kotlin = "6.1.0"
okio= "3.16.3"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
stonecutter = { module = "dev.kikugie.stonecutter:dev.kikugie.stonecutter.gradle.plugin", version.ref = "stonecutter" }
architectury-loom = { module = "dev.architectury.loom:dev.architectury.loom.gradle.plugin", version.ref = "architectury-loom" }
mod-publish = { module = "me.modmuss50.mod-publish-plugin:me.modmuss50.mod-publish-plugin.gradle.plugin", version.ref = "mod-publish" }

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
